---
version: "2"
run:
  timeout: 10m

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    # TODO: decide about import order and enable the linter
    # - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomoddirectives
    - goprintffuncname
    - gosec
    - ifshort
    # Not full go1.18 support, disable for a while
    # - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - thelper
    - unconvert
    - unparam
    - wastedassign
    - wrapcheck
  exclusions:
    rules:
      - path: internal/worker/notifier/param.go
        # TODO: Remove nolint (linter not supports go1.18 features)
        linters:
          - typecheck

      - path: _test\.go
        linters:
          - dupl
          - errcheck
          - forcetypeassert
          - funlen
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gocyclo
          - goerr113
          - ifshort
          - ireturn
          - lll

  settings:
    nolintlint:
      require-explanation: true
      require-specific: true

    errcheck:
      check-blank: true

    govet:
      enable:
        - shadow

    nakedret:
      max-func-lines: 0

    tagliatelle:
      case:
        rules:
          json: snake
          bson: snake

    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - multierr.Append(
        - multierr.Combine(
        - (*whereiseveryone/internal/webapi/jsonerr.JSONError).Echo(
        - endpoints.
        - (github.com/labstack/echo/v4.Context).JSON(
        - (github.com/labstack/echo/v4.Context).String(
        - (github.com/labstack/echo/v4.Context).NoContent(

    revive:
      confidence: 0.8
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
