// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "logs in as an exiting users using login and passowrd",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "log in",
                "parameters": [
                    {
                        "description": "login details",
                        "name": "userDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.logInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.authResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "403": {
                        "description": "forbidden (invalid password)",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "404": {
                        "description": "user not exists",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "409": {
                        "description": "device token conflict; session revoked, log in again",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "requires the current refresh-purpose token and bound device_token; replaces both tokens and revokes previous access tokens",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "refresh auth tokens",
                "parameters": [
                    {
                        "description": "refresh token",
                        "name": "refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.refreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.authResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "403": {
                        "description": "invalid refresh token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "404": {
                        "description": "user not exists",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "409": {
                        "description": "device token conflict; session revoked, log in again",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "creates a new user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "sign up as a new user",
                "parameters": [
                    {
                        "description": "sign up details",
                        "name": "userDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.signUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.authResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "409": {
                        "description": "conflict (user with such a name exists)",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/friend": {
            "post": {
                "description": "sends friend request to another user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "send friend request",
                "parameters": [
                    {
                        "description": "user to friend",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.friendRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "404": {
                        "description": "requested user not exists",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            },
            "delete": {
                "description": "removes friend and clears pending requests between users",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "remove friend",
                "parameters": [
                    {
                        "description": "user to unfriend",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.friendRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "404": {
                        "description": "requested user not exists",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/friend/accept": {
            "post": {
                "description": "accepts pending friend request from another user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "accept friend request",
                "parameters": [
                    {
                        "description": "user to accept",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.friendRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "404": {
                        "description": "requested user not exists",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/friend/reject": {
            "post": {
                "description": "rejects pending friend request from another user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "reject friend request",
                "parameters": [
                    {
                        "description": "user to reject",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.friendRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "404": {
                        "description": "requested user not exists",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/friends": {
            "get": {
                "description": "returns accepted friends and pending friend requests",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "get friends details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/me.friendDetails"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/location": {
            "put": {
                "description": "update logged user location",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "update location",
                "parameters": [
                    {
                        "description": "update location object",
                        "name": "location",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.updateLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            },
            "delete": {
                "description": "nullify logged user location",
                "tags": [
                    "me"
                ],
                "summary": "wipe location",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/sharing": {
            "get": {
                "description": "returns list of friends with whom location sharing is paused",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "get paused friends details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/me.pausedFriendDetails"
                            }
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/sharing/resume": {
            "post": {
                "description": "resume sharing location with another user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "resume sharing location",
                "parameters": [
                    {
                        "description": "user to resume sharing with",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.friendRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/sharing/stop": {
            "post": {
                "description": "stop sharing location with another user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "stop sharing location",
                "parameters": [
                    {
                        "description": "user to stop sharing with",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.friendRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        },
        "/me/status": {
            "put": {
                "description": "updates logged user status (text status)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "me"
                ],
                "summary": "update status",
                "parameters": [
                    {
                        "description": "update status object",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/me.updateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "401": {
                        "description": "invalid token",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/jsonerr.JSONError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.authResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID is user id (uuid)",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "RefreshToken refresh-only token for /auth/refresh; cannot be used as a Bearer token",
                    "type": "string"
                },
                "token": {
                    "description": "Token access token for Bearer authentication; must match the current stored session",
                    "type": "string"
                }
            }
        },
        "auth.logInRequest": {
            "type": "object",
            "required": [
                "device_token",
                "password",
                "username"
            ],
            "properties": {
                "device_token": {
                    "description": "DeviceToken is a required, nonblank client device identifier for single-device auth",
                    "type": "string"
                },
                "password": {
                    "description": "Password user password",
                    "type": "string"
                },
                "username": {
                    "description": "Username",
                    "type": "string"
                }
            }
        },
        "auth.refreshTokenRequest": {
            "type": "object",
            "required": [
                "device_token",
                "refresh_token"
            ],
            "properties": {
                "device_token": {
                    "description": "DeviceToken is required and must match the device bound to the current session",
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "auth.signUpRequest": {
            "type": "object",
            "required": [
                "device_token",
                "password",
                "username"
            ],
            "properties": {
                "device_token": {
                    "description": "DeviceToken is a required, nonblank client device identifier for single-device auth",
                    "type": "string"
                },
                "password": {
                    "description": "Password user password, min 8 characters",
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "description": "Username username, must be unique",
                    "type": "string"
                }
            }
        },
        "jsonerr.JSONError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is desired http code for this error",
                    "type": "integer"
                },
                "error": {
                    "description": "Err is a golang error returned by the app\nIt is removed in production application (TBD)",
                    "type": "string"
                },
                "message": {
                    "description": "Message is human friendly error message",
                    "type": "string"
                }
            }
        },
        "me.friendDetails": {
            "type": "object",
            "properties": {
                "friend_since": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/me.locationDetails"
                },
                "state": {
                    "$ref": "#/definitions/me.friendState"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "me.friendRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "me.friendState": {
            "type": "string",
            "enum": [
                "accepted",
                "pending_incoming",
                "pending_outgoing"
            ],
            "x-enum-varnames": [
                "friendStateAccepted",
                "friendStatePendingIncoming",
                "friendStatePendingOutgoing"
            ]
        },
        "me.locationDetails": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "altitude": {
                    "type": "number"
                },
                "bearing": {
                    "type": "number"
                },
                "last_update": {
                    "description": "LastUpdate in UTC time",
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                }
            }
        },
        "me.pausedFriendDetails": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "me.updateLocationRequest": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "number"
                },
                "altitude": {
                    "type": "number"
                },
                "bearing": {
                    "type": "number"
                },
                "last_update": {
                    "description": "LastUpdate in UTC time",
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "speed": {
                    "type": "number"
                }
            }
        },
        "me.updateStatusRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "WhereIsEveryone",
	Description:      "This is a sample server for WhereIsEveryone",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
